// <auto-generated />
namespace Bolao.Cup.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class primeiramigracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primeiramigracao));
        
        string IMigrationMetadata.Id
        {
            get { return "201705020311144_primeira migracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
